'use strict';

const SystemInfo = {
  ServiceUserName: process.env.SERVICE_USERNAME || '',
  ServicePassword: process.env.SERVICE_PASSWORD || '',
  CurrentLanguage: 'zh-CN',
  Themes: '',
  UpdateVisit: true,
  OnLineTime0ut: 2 * 60 + 20,
  OnLineLimit: 0,
  EnableCheckPasswordStrength: false,
  EnableCheckIPAddress: false,
  CheckOnLine: false,
  EnableEncryptServerPassword: true,
  PasswordErrorLockLimit: 5,
  PasswordErrorLockCycle: 30,
  EnableOrganizePermission: true,
  LogOned: false,
  OnLineState: 0,
  RememberPassword: true,
  AutoLogOn: false,
  EncryptClientPassword: true,
  ServiceUserNameClient: process.env.CLIENT_SERVICE_USERNAME || '',
  ServicePasswordClient: process.env.CLIENT_SERVICE_PASSWORD || '',
  LoadAllUser: true,
  OrganizeDynamicLoading: true,
  MultiLanguage: false,
  ThemesClient: '',
  lockWaitMinute: 60,
  WebHostUrl: 'WebHostUrl',
  ShowExceptionDetail: true,
  ShowSuccessMsg: true,
  PageSize: 50,
  ConfigFile: 'Config',
  Host: '',
  Port: 0,
  AllowUserToRegister: true,
  UseMessage: true,
  EnableUserAuthorizationScope: false,
  EnableUserAuthorization: true,
  EnableModulePermission: true,
  EnablePermissionItem: true,
  EnableTableConstraintPermission: false,
  EnableTableFieldPermission: false,
  EnableHandWrittenSignature: true,
  EnableRecordLogOnLog: true,
  EnableRecordLog: true,
  LogException: true,
  LogSQL: false,
  EventLog: false,
  DefaultPassword: '',
  PasswordMiniLength: 6,
  NumericCharacters: true,
  PasswordChangeCycle: 3,
  AccountMinimumLength: 4,
  EncryptDbConnection: false,
  RDIFrameworkDbConection: '',
  RDIFrameworkDbConectionString: '',
  BusinessDbConnection: '',
  BusinessDbConnectionString: '',
  WorkFlowDbConnection: '',
  WorkFlowDbConnectionString: '',
  NeedRegister: true,
  OnLineCheck: 60,
  RegisterKey: '',
  StartupPath: '',
  MatchCase: true,
  TopLimit: 200,
  LockNoWaitCount: 5,
  LockNoWaitTickMilliSeconds: 30,
  ServerCache: false,
  LastUpdate: '2016.02.18',
  Version: '3.0',
  ShowInformation: true,
  TimeFormat: 'HH:mm:ss',
  DateFormat: 'yyyy-MM-dd',
  DateTimeFormat: 'yyyy-MM-dd HH:mm:ss',
  SoftName: '',
  SoftFullName: '',
  RootMenuCode: '',
  ClientCache: false,
  CustomerCompanyName: '',
  AppIco: 'Resource\\App.ico',
  AddInDirectory: 'AddIn\\',
  RegisterException: '请您联系： 手机： 电子邮件： 对软件进行注册。',
  CustomerPhone: '',
  CompanyName: '',
  CompanyPhone: '',
  Copyright: 'Copyright 2009-2016 ',
  HelpNamespace: '',
  UploadDirectory: 'Document/',
  MainAssembly: '',
  MainForm: 'FrmRDIFrameworkNav',
  LogOnAssembly: 'RDIFramework.NET',
  LogOnForm: 'FrmLogOn',
  Service: 'RDIFramework.BizLogic',
  ServiceFactory: 'ServiceFactory',
  DbProviderAssmely: 'RDIFramework.Utilities',
  CurrentStyle: 'VisualStudio2010Blue',
  CurrentThemeColor: '',
  ErrorReportFrom: '',
  ErrorReportMailServer: 'smtp.126.com',
  ErrorReportMailUserName: 'umplatform@126.com',
  ErrorReportMailPassword: '',
  RDIFrameworkBlog: '',
  RDIFrameworkWeibo: '',
  NodeTimeout: '72'
};

module.exports = SystemInfo;
