ALTER TABLE `poleis_session`
    ADD COLUMN `RELAYNODEID` VARCHAR(40) NULL,
    ADD COLUMN `RELAYBYTES` BIGINT NOT NULL DEFAULT 0;

CREATE TABLE `poleis_relay_node` (
    `ID` VARCHAR(40) NOT NULL,
    `TENANTID` VARCHAR(40) NOT NULL DEFAULT 'default',
    `NAME` VARCHAR(100) NOT NULL,
    `HOST` VARCHAR(200) NOT NULL,
    `PORT` INTEGER NOT NULL DEFAULT 3478,
    `TLSPORT` INTEGER NULL,
    `REGION` VARCHAR(40) NULL,
    `LATITUDE` DOUBLE NULL,
    `LONGITUDE` DOUBLE NULL,
    `WEIGHT` INTEGER NOT NULL DEFAULT 100,
    `MAXBANDWIDTHKBPS` INTEGER NOT NULL DEFAULT 0,
    `STATICSECRET` VARCHAR(200) NULL,
    `REALM` VARCHAR(100) NULL,
    `STATUS` VARCHAR(20) NOT NULL DEFAULT 'offline',
    `LASTHEARTBEAT` DATETIME(0) NULL,
    `LASTLATENCYMS` INTEGER NULL,
    `ACTIVESESSIONS` INTEGER NOT NULL DEFAULT 0,
    `TOTALBYTES` BIGINT NOT NULL DEFAULT 0,
    `ENABLED` INTEGER NOT NULL DEFAULT 1,
    `DELETEMARK` INTEGER NOT NULL DEFAULT 0,
    `CREATEON` TIMESTAMP(0) NULL DEFAULT CURRENT_TIMESTAMP(0),
    `CREATEUSERID` VARCHAR(50) NULL,
    `CREATEBY` VARCHAR(50) NULL,
    `MODIFIEDON` DATETIME(0) NULL,
    `MODIFIEDUSERID` VARCHAR(50) NULL,
    `MODIFIEDBY` VARCHAR(50) NULL,

    INDEX `poleis_relay_node_TENANTID_idx` (`TENANTID`),
    INDEX `poleis_relay_node_REGION_idx` (`REGION`),
    INDEX `poleis_relay_node_STATUS_idx` (`STATUS`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
